### ISSUE TITLE
Failed to get completion response: from_response

### ISSUE THREAD

**Issue by aidando73** [aorwall/moatless-tree-search#17]
Trying to run moatless with a custom LLM

```
from moatless.agent.code_agent import CodingAgent
from moatless.agent.code_prompts import SIMPLE_CODE_PROMPT
from moatless.benchmark.swebench import create_repository
from moatless.benchmark.utils import get_moatless_instance
from moatless.completion import CompletionModel
from moatless.file_context import FileContext
from moatless.index import CodeIndex
from moatless.search_tree import SearchTree
from moatless.actions import FindClass, FindFunction, FindCodeSnippet, SemanticSearch, ViewCode, StringReplace, CreateFile, AppendString, RunTests, Finish, Reject
import os
import dotenv

dotenv.load_dotenv()

index_store_dir = "/tmp/index_store"
repo_base_dir = "/tmp/repos"
persist_path = "trajectory.json"

instance = get_moatless_instance("django__django-16379")

completion_model = CompletionModel(
    model="openai/accounts/fireworks/models/llama-v3p1-405b-instruct",
    temperature=0.0,
    model_base_url=os.getenv("CUSTOM_LLM_API_BASE"),
    model_api_key=os.getenv("CUSTOM_LLM_API_KEY")
)

repository = create_repository(instance)

code_index = CodeIndex.from_index_name(
    instance["instance_id"], index_store_dir=index_store_dir, file_repo=repository
)

actions = [
    FindClass(code_index=code_index, repository=repository),
    FindFunction(code_index=code_index, repository=repository),
    FindCodeSnippet(code_index=code_index, repository=repository),
    SemanticSearch(code_index=code_index, repository=repository),
    ViewCode(repository=repository),
    StringReplace(repository=repository, code_index=code_index),
    CreateFile(repository=repository, code_index=code_index),
    AppendString(repository=repository, code_index=code_index),
    RunTests(repository=repository, code_index=code_index),
    Finish(),
    Reject()
]

file_context = FileContext(repo=repository)
agent = CodingAgent(
    actions=actions,
    completion=completion_model,
    system_prompt=SIMPLE_CODE_PROMPT,

)

search_tree = SearchTree.create(
    message=instance["problem_statement"],
    agent=agent,
    file_context=file_context,
    max_expansions=1,
    max_iterations=50
)

node = search_tree.run_search()
print(node.observation.message)
```

But getting this error:

```
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/aidand/dev/moatless-tree-
[nltk_data]     search/env/lib/python3.12/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Package punkt_tab is already up-to-date!
Completion attempt failed with error: from_response. Will retry.
Traceback (most recent call last):
  File "/Users/aidand/dev/moatless-tree-search/moatless/completion/completion.py", line 330, in _do_completion
    response = response_model.from_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 320, in __getattr__
    raise AttributeError(item)
AttributeError: from_response
Completion attempt failed with error: from_response. Will retry.
Traceback (most recent call last):
  File "/Users/aidand/dev/moatless-tree-search/moatless/completion/completion.py", line 330, in _do_completion
    response = response_model.from_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 320, in __getattr__
    raise AttributeError(item)
AttributeError: from_response
Completion attempt failed with error: from_response. Will retry.
Traceback (most recent call last):
  File "/Users/aidand/dev/moatless-tree-search/moatless/completion/completion.py", line 330, in _do_completion
    response = response_model.from_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 320, in __getattr__
    raise AttributeError(item)
AttributeError: from_response
Traceback (most recent call last):
  File "/Users/aidand/dev/moatless-tree-search/moatless/completion/completion.py", line 361, in _litellm_completion
    return retries(_do_completion)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x34fc6a270 state=finished raised CompletionRuntimeError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aidand/dev/moatless-tree-search/app.py", line 64, in <module>
    node = search_tree.run_search()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/moatless/search_tree.py", line 110, in run_search
    self._simulate(new_node)
  File "/Users/aidand/dev/moatless-tree-search/moatless/search_tree.py", line 170, in _simulate
    self.agent.run(node)
  File "/Users/aidand/dev/moatless-tree-search/moatless/agent/agent.py", line 109, in run
    node.action, completion_response = self._completion.create_completion(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/moatless/completion/completion.py", line 157, in create_completion
    raise e
  File "/Users/aidand/dev/moatless-tree-search/moatless/completion/completion.py", line 153, in create_completion
    action_args, completion_response = self._litellm_completion(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/moatless/completion/completion.py", line 363, in _litellm_completion
    raise e.reraise()
          ^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/aidand/dev/moatless-tree-search/env/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/aidand/dev/moatless-tree-search/moatless/completion/completion.py", line 356, in _do_completion
    raise CompletionRuntimeError(
moatless.exceptions.CompletionRuntimeError: Failed to get completion response: from_response
```

Any ideas why?

**Comment by aorwall** [comment]
I've reworked some code to provide solid support for DeepSeek v3. Hopefully, it should work well with other open-source models too. In  [integration_test.py](https://github.com/aorwall/moatless-tree-search/blob/main/tests/integration_test.py) you can see which models I've verified.
