### ISSUE TITLE
reject action need scratch pad

### ISSUE THREAD

**Issue by xinpeng-zhang** [aorwall/moatless-tree-search#5]
Traceback (most recent call last):
  File "/Users/xinpengzhang/Project/moatless-tree-search/test.py", line 58, in <module>
    node = search_tree.run_search()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xinpengzhang/Project/moatless-tree-search/moatless/search_tree.py", line 223, in run_search
    self._simulate(new_node)
  File "/Users/xinpengzhang/Project/moatless-tree-search/moatless/search_tree.py", line 284, in _simulate
    self.agent.run(node)
  File "/Users/xinpengzhang/Project/moatless-tree-search/moatless/agent/agent.py", line 98, in run
    node.action = RejectArgs(rejection_reason=rejection_reason)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/main.py", line 213, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Reject
scratch_pad
  Field required [type=missing, input_value={'rejection_reason': 'Ins...ailed after 3 attempts'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
    
    
I guess when assigning reject args, still need to assigning scratch pad value.
Not sure the reason here.
It looks like Reject class properly inherits from Action

**Comment by xinpeng-zhang** [comment]
I did this
node.action = RejectArgs(scratch_pad = rejection_reason, rejection_reason=rejection_reason)

**Comment by aorwall** [comment]
I merged some changes now where I hope this will be solved

**Comment by xinpeng-zhang** [comment]
I appreciate it, this is the best work I have even seen in repository level code tasks.
